In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2022-04-29 16:52:57.775256: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-29 16:52:57.778029: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [6]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        keras.Input(shape=(4,)),
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

ValueError: Input 0 of layer "sequential_1" is incompatible with the layer: expected shape=(None, 4), found shape=(3, 3)

In [3]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [4]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.6291832 ,  1.905466  , -1.0241143 , -0.58924526],
       [ 0.6291832 ,  1.905466  , -1.0241143 , -0.58924526],
       [ 0.6291832 ,  1.905466  , -1.0241143 , -0.58924526]],
      dtype=float32)>